### ISSUE TITLE
rpc error: code = Unavailable desc = transport is closing

### ISSUE THREAD

**Issue by manu4gmz** [jason-shen/ion-sfu-nodejs#2]
I'm trying to get the example demo working ([this demo](https://github.com/jason-shen/ion-sfu-nodejs-example)) and I had a problem in my local machine so I tested it on a AWS Lightsail virtual machine.

In both places I'm running `ion-sfu` with docker with the following command

```
$ sudo docker run -p 50051:50051 -p 5000-5200:5000-5200/udp pionwebrtc/ion-sfu:latest-grpc
```
On both clients it correctly connects through WebSocket to the NodeJs server, but when any of them tried to **publish** it's media, on the docker logs the following error appeared:
```
negotiation error error="rpc error: code = Unavailable desc = transport is closing"
```
Logically, after that, if the other client tried to publish, on the browser it logs the following error: ```(index):218 WebSocket is already in CLOSING or CLOSED state.```

However, the ion-sfu is logging and answering other events, like `Peer join session `, `Peer got offer`, `Negotiation needed`, `Send offer`, `On subscriber ice candidate called for peer` (this last one occurs after the error).

I'm pretty sure **it's not a matter of UDP ports rules setting**, because it happens also on my local machine (anyways, on the aws I checked for the iptables and all from 5000 to 5200 are correctly enabled for UDP)

I hope anyone can help me, I'll provide any specifications needed if it helps :)

(AWS) Node version 12.20.2
(AWS) Docker version 20.10.6

(Local) Node version 10.13.0
(Local) Docker version 19.03.13

(both) Ion sfu nodejs version 0.0.5
(both) Ion sfu version 1.9.8

**Comment by jason-shen** [comment]
Ok I see what the problem is, it's the ion-sfu had been updated, if u just want to get start it please use this version until I update the package https://github.com/pion/ion-sfu/releases/tag/v1.8.0

**Comment by manu4gmz** [comment]
Thanks for replying! I read that on an another response of yours in your yt video, but I didn't think it applied on this case. I'll look into it and comment here if it works

**Comment by jason-shen** [comment]
It should work, but do let me know after you test cheers 

I will see if I can upgrade it alone with the latest

**Comment by manu4gmz** [comment]
Thank u you so much! Now it works like a charm on my localhost

For those using docker for ios-sfu here is the comand with the tag that worked for me
```
$ sudo docker run -p 50051:50051 -p 5000-5200:5000-5200/udp pionwebrtc/ion-sfu:v1.8.0-grpc
```
---


Now, sadly it doesn't work in my AWS Lightsail (Probably it's networking stuff)

I used the following command to append the rules to iptables
```
sudo iptables -A INPUT -p udp --match multiport --dports 5000:5200 -j ACCEPT \
sudo iptables -A OUTPUT -p udp --match multiport --sports 5000:5200 -j ACCEPT
```

Using `sudo iptables --list` this is what I get:

```
Chain INPUT (policy ACCEPT)
...
ACCEPT     udp  --  anywhere             anywhere             multiport dports 5000:5200

Chain OUTPUT (policy ACCEPT)     
...
ACCEPT     udp  --  anywhere             anywhere             multiport sports 5000:5200
```
> I get this is not related to the issue, if you like, I'll move it to another issue (I think having as many issues solved posted to help people on the future is important) or if you think it has nothing to do with the package I'll remove it

**Comment by jason-shen** [comment]
Either way I'm happy with it, as long as it can help others, btw I'm planning a full on tut doing a real zoom clone soon, if you interested follow me on Twitter, I will update on there

**Comment by manu4gmz** [comment]
I'll see it on YT, keep it up! Cheers from Argentina

**Comment by jason-shen** [comment]
I think you should run it with out docker first make sure it all works, some times docker is an problem by it self especially when it comes to networking m, it's a nightmare, good luck
